name: QTL_Test

channels: 
  - bioconda
  - conda-forge
  - defaults
  - r
#  - guibar

dependencies: 
  - snakemake=4.3.1
  - bcftools=1.9
  - r-devtools
  - r-ggplot2
  - r-vcfr
  - bioconductor-VariantAnnotation
#  - r-QTLseqr
  - r-yaml
  - r-data.table
