channels: 
  - bioconda
  - conda-forge
  - defaults
  - r
  
dependencies: 
 # - snakemake=3.9.0
  - bcftools=1.3.1
  - r-devtools
  - r-ggplot2
  - r-vcfr
  - bioconductor-VariantAnnotation
 # - r-QTLseqr
  - r-yaml
  - r-data.table
