name: QTL

channels: 
  - defaults
  - bioconda
  - conda-forge
  - r
#  - guibar

dependencies:
  - r-base
  - r-rlang=0.4.6 
  - python=3.6.7
#  - snakemake
  - bcftools
  - r-devtools
  - r-ggplot2
  - r-vcfR
  - bioconductor-VariantAnnotation
#  - r-QTLseqr
  - r-yaml
  - r-data.table
  - pandas
  - matplotlib
  - seaborn
